sudo: required

language: java

services:
- docker

before_install:
- docker build sepsyk/reverse .
- docker run -d -p 127.0.0.1:8081:8081 sepsyk/reverse

script:
- curl -s -o /dev/null -X POST -d '{"message": "something"}' http://127.0.0.1:8081/reverse -w "%{http_code}"
